apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - infra
  - navidrome
  - jellyfin
  - prowlarr
  - nzbget
  - sonarr
  - radarr
  - lidarr
  - tdarr
  - slskd
