apiVersion: v1
kind: Secret
metadata:
    name: nzbget
stringData:
    NZBGET_USER: ENC[AES256_GCM,data:PTidwhYu,iv:QEXkqPxWmfSVdqA1mkuXgXc20U3wBBf8W4+WuUZENYA=,tag:x4oFyo43oht871MgdTaybQ==,type:str]
    NZBGET_PASS: ENC[AES256_GCM,data:rGVrMpolrYE=,iv:ah93cfKDGyu76UbxNqpub+aW8UeVkeEJy3mUQDYQH58=,tag:koNH9sfpoQfN63OC4bRhbQ==,type:str]
sops:
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTW5uMlpIck9ULy9SOGpX
            aEhsMjcrZDAzUTBVS0NzWnRkdWJLUWFzR21vCmdLbkMrTmg3Wm9ReE80ZDR2SUU5
            UjlLMk1vbllEWGFMZ1ZqWmdHd0l2N1UKLS0tIHdZMGIxV0NWV0Z5cHZlOEM3bkMz
            V2lrU0RrRWxlWlRxSHRmTlB3aVNBOFUKIeqkeejFBqSnF8hOu+DVV/a0lsOjlU4s
            Gm62deBq61eIRUhrF4CeFUOhnGGRMXbiQ0HIgKgNXkYuoHvEjC4yDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T19:42:44Z"
    mac: ENC[AES256_GCM,data:1cweNFtOw3GZZP12KcNYStLPsgo1cvyJq/EUTEPFzyMIE1eS13iVCyxEiqFkHu1ZcP/0Fre4sRJICay7K5UNuHEo9XC/zxNffm9QLkX0xZVtBzLFuX2fyg6mgdrM89dqGhd+uqGByD6JBQq+bCy9mLOovkI49g/+eYgMInDDHbg=,iv:cX0hOX8N1st9v+xrhcUoNop1+Wn+K8HxyRqSPGq+PDo=,tag:8rn2RR1kytRRqoAc/RrGCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
