apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: element
spec:
  interval: 15m
  chart:
    spec:
      chart: matrix-synapse
      version: "3.12.18" # (versions found here) https://artifacthub.io/packages/helm/ananace-charts/matrix-synapse
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: infra
  values:
    serverName: "matrix.raphael-bader.com"
    publicServerName: "matrix.raphael-bader.com"

    config:
      enableRegistration: false
      enableRegistrationWithoutVerification: true
  
      extraConfig:
        suppress_key_server_warning: true
        turn_uris:
          - "turn:global.relay.metered.ca:80?transport=udp"
          - "turn:global.relay.metered.ca:80?transport=tcp"
          - "turn:global.relay.metered.ca:443?transport=udp"
          - "turns:global.relay.metered.ca:443?transport=tcp"

  valuesFrom:
    - kind: Secret
      name: matrix-synapse-secrets
      valuesKey: registration-shared-secret
      targetPath: config.registrationSharedSecret
    
    - kind: Secret
      name: matrix-synapse-secrets
      valuesKey: turn-username
      targetPath: config.extraConfig.turn_user
    
    - kind: Secret
      name: matrix-synapse-secrets
      valuesKey: turn-password
      targetPath: config.extraConfig.turn_pass
