apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: element
spec:
  interval: 15m
  chart:
    spec:
      chart: matrix-synapse
      version: "3.12.18" # (versions found here) https://artifacthub.io/packages/helm/ananace-charts/matrix-synapse
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: infra
  values:
    serverName: "matrix.raphael-bader.com"
    publicServerName: "matrix.raphael-bader.com"

    turn:
      enabled: true
      uris:
      - "turn:matrix.raphael-bader.com:3478?transport=udp"
      - "turn:matrix.raphael-bader.com:3478?transport=tcp"

    config:
      enableRegistration: false
      enableRegistrationWithoutVerification: true
  
    extraConfig:
      suppress_key_server_warning: true

    
    
    postgresql:
      enabled: true
      persistence:
        size: 75Gi

  valuesFrom:
    - kind: Secret
      name: matrix-synapse-secrets
      valuesKey: registration-shared-secret
      targetPath: config.registrationSharedSecret

    - kind: Secret
      name: matrix-synapse-secrets
      valuesKey: turn-shared-secret
      targetPath: turn.staticSecret
