apiVersion: v1
kind: Secret
metadata:
    name: matrix-synapse-secrets
    namespace: element
type: Opaque
stringData:
    registration-shared-secret: ENC[AES256_GCM,data:eKEno6pFfque5GyOewz1hLRoyorqSNZB8J9VSTANLZU=,iv:gbYkv9v3SFS8sQLsebloh80WqoXZkh1Z/4FY9hdceFs=,tag:0O7s8aYVPSm54mZv1NDVCA==,type:str]
    turn-username: ENC[AES256_GCM,data:25WShJ9/4t7PfgzTN+R8BEMerrfU5605,iv:ptkCNBLZotek19738EkD8a6DDHGOLNSid4QVBzhscFk=,tag:Su/kzhAYzD4X/BX/npus7A==,type:str]
    turn-password: ENC[AES256_GCM,data:tPxQVyn/SOa1Ev3vrJsEaQ==,iv:dHFmqEGAi9twMs8gMHRsvk68Z1ro7e0ewv14imSjCG8=,tag:Ax4f2JjRYd4p+QopcWMZwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZC9Ldk9uNXhCS1h4ZGV0
            SDNLN2VXaUFGbDV2aldOVWF4d3ozR1lJUjBRCkMvL3pjbGhDdGE3SytYd3ZmdmE2
            WVNwQkNITHhQYkx5MG8wUm5aUUE1bkEKLS0tIDJBNXZwdVdJTnJkWFVRRmlsSk5M
            b0JYaFZ2Vmp3aFEzUWhuMDVJQmRaUUkKNqsLbumU12nmPPfCfW+NTdutAH/6Xlrt
            RGvPSEQNmu/OCREUfnhp9DJoJ7UYqubJD33DJNTmAeMuCUsxf3gI5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T20:08:47Z"
    mac: ENC[AES256_GCM,data:4ZdZCSymqtPHsNhT6z/xqMd1eHJQ33yRqnCmEWrumkqVH+pd33aWvty1lYAfZGNJbffSEF5LC/xAhwWn2YV35iPF3vfkqlxeJVxz8XNXRbG5Kth7CNzt5ligjKryOBLVw3p6F8bf3upRh9leM/o+X9/9ZbXp73wHq3r1KgBdAnY=,iv:brAoFdBd4NVQNICz4+Y3vKlw9pDbQBO2jNKjYniRB6c=,tag:nvDdTGIuxr0etNhWFtezuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
