apiVersion: v1
kind: Secret
metadata:
    name: matrix-synapse-secrets
    namespace: element
type: Opaque
stringData:
    registration-shared-secret: ENC[AES256_GCM,data:eKEno6pFfque5GyOewz1hLRoyorqSNZB8J9VSTANLZU=,iv:gbYkv9v3SFS8sQLsebloh80WqoXZkh1Z/4FY9hdceFs=,tag:0O7s8aYVPSm54mZv1NDVCA==,type:str]
    turn-shared-secret: ENC[AES256_GCM,data:K91YJe0muOxNEq5rE+9t7XK4D75HABs0DMCpO1QdaO/bTM8r3fOZWTNc4Nk=,iv:TzLy2qVmP7SndMla/lZOlb9bpkR/X2PqMN/MwdOHdQU=,tag:uPtdK+FmCk/W9G3B53HA7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZC9Ldk9uNXhCS1h4ZGV0
            SDNLN2VXaUFGbDV2aldOVWF4d3ozR1lJUjBRCkMvL3pjbGhDdGE3SytYd3ZmdmE2
            WVNwQkNITHhQYkx5MG8wUm5aUUE1bkEKLS0tIDJBNXZwdVdJTnJkWFVRRmlsSk5M
            b0JYaFZ2Vmp3aFEzUWhuMDVJQmRaUUkKNqsLbumU12nmPPfCfW+NTdutAH/6Xlrt
            RGvPSEQNmu/OCREUfnhp9DJoJ7UYqubJD33DJNTmAeMuCUsxf3gI5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T19:42:13Z"
    mac: ENC[AES256_GCM,data:tMF2Pn1lX/xdz0ufJEtENBynLAgVf1scXVzjBMfOifOgG1qeXXdJgAKlNaXdJUEy5lmbdUR2D1yKHMGoPx+8dKs1+izmgHJwWEw0dzr0hVVmntrSbBluAS6gQzJU3Ckvxjop5lAPl6xLCq4wwu5o/G8sf0wAdTcYfPojFB4cw90=,iv:T22E2qoTS9ATg6l9FlXJ2X+Z4IaFOuypGuAfMwULtZw=,tag:gzb/3JAXSZ9H/9Dm1uG1NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
