apiVersion: v1
kind: Secret
metadata:
    name: matrix-synapse-secrets
    namespace: element
type: Opaque
stringData:
    registration-shared-secret: ENC[AES256_GCM,data:eKEno6pFfque5GyOewz1hLRoyorqSNZB8J9VSTANLZU=,iv:gbYkv9v3SFS8sQLsebloh80WqoXZkh1Z/4FY9hdceFs=,tag:0O7s8aYVPSm54mZv1NDVCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZC9Ldk9uNXhCS1h4ZGV0
            SDNLN2VXaUFGbDV2aldOVWF4d3ozR1lJUjBRCkMvL3pjbGhDdGE3SytYd3ZmdmE2
            WVNwQkNITHhQYkx5MG8wUm5aUUE1bkEKLS0tIDJBNXZwdVdJTnJkWFVRRmlsSk5M
            b0JYaFZ2Vmp3aFEzUWhuMDVJQmRaUUkKNqsLbumU12nmPPfCfW+NTdutAH/6Xlrt
            RGvPSEQNmu/OCREUfnhp9DJoJ7UYqubJD33DJNTmAeMuCUsxf3gI5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T20:24:36Z"
    mac: ENC[AES256_GCM,data:A1DAdWcL23wgWV3pjNpmsOKBJ37rAjIosWzw7iiJeZV+aRX60rc2No2Qd+gKL0IsBfcHiABcP/Ug7NN3fQHFfyCxXcFfCqNqLaTysDxaLOgrKKmJnzSophC6BhQW7pterHJKcAPmUskfHNeHPgTA4oAMFVH3hkwWunODFcauFQc=,iv:1ZJ6s+/bkEUewj5w/w5rAXkjsEy1AFD+6pja8UEvcb0=,tag:nUfZOOIRm73Ji3P+M7ceAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
