apiVersion: v1
kind: Secret
metadata:
    name: koito-alex
stringData:
    KOITO_SUBSONIC_PARAMS: ENC[AES256_GCM,data:hdFZ3TpAyRJwr289EXv/OGvN0Q7tNNCKpCZ217232gqs4a52KtD7iumd0Z09UZxPvnJD,iv:xYUSLv36VuCbvIh0uWTlz0Q35txkrqm5TXz8xllJUFk=,tag:HEcIhvfI8Yml/CGEJ8HncQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTW5uMlpIck9ULy9SOGpX
            aEhsMjcrZDAzUTBVS0NzWnRkdWJLUWFzR21vCmdLbkMrTmg3Wm9ReE80ZDR2SUU5
            UjlLMk1vbllEWGFMZ1ZqWmdHd0l2N1UKLS0tIHdZMGIxV0NWV0Z5cHZlOEM3bkMz
            V2lrU0RrRWxlWlRxSHRmTlB3aVNBOFUKIeqkeejFBqSnF8hOu+DVV/a0lsOjlU4s
            Gm62deBq61eIRUhrF4CeFUOhnGGRMXbiQ0HIgKgNXkYuoHvEjC4yDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T23:55:17Z"
    mac: ENC[AES256_GCM,data:S3/lBU4WDzszfIQ+Qm2aTG6Fy1k4JZwpcRVOwwd5Kemo7g/vj7KQbtFmvArySlscbxjFeqy/3KXZXEoUDcQDpE10MaBz5j8g5b0YVUbzAONxreAt7zIGx3QAkUhaBHslG0T0N/Lk4zefJGTWF56qs+i0kN04cY/t1kniQmZIwPU=,iv:xgSBVjfLZLThd5Nck0fuF6Zw5SiQJ9xS/955p68vj8o=,tag:Hs53rQ0qUWKHzeDojSkMYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
