apiVersion: apps/v1
kind: Deployment
metadata:
  name: koito
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: koito
  template:
    metadata:
      labels:
        app: koito
    spec:
      containers:
        - name: koito
          image: ghcr.io/gabehf/koito:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: http
              containerPort: 4110
          volumeMounts:
            - name: koito-data
              mountPath: /etc/koito
      volumes:
        - name: koito-data
          persistentVolumeClaim:
            claimName: koito-pvc
