apiVersion: v1
kind: Service
metadata:
  name: koito
spec:
  selector:
    app: koito
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: koito-tailscale
  annotations:
    tailscale.com/funnel: "true" 
spec:
  defaultBackend:
    service:
      name: koito
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
      - koito
