apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
spec:
  capacity:
    storage: "500Gi"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/beelink/mediacenter_downloads
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "500Gi"
  storageClassName: ""
  volumeName: downloads
