apiVersion: v1
kind: PersistentVolumeClaim # removed and changed to emptyDir, cause idc if i lose a single movie if a node goes down
metadata:
  name: incomplete
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "150Gi"
