apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - music-pvc.yaml
  - media-pvc.yaml
  - youtube-pvc.yaml
  - tv-pvc.yaml
  - movie-pvc.yaml
  - download-pvc.yaml
  - incomplete-pvc.yaml
  - transcoded-movies-pvc.yaml
  - soulseek-download-pvc.yaml
