apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: "5Ti"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/hdd/shared/mediacenter/media
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "5Ti"
  storageClassName: ""
  volumeName: media
