apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
spec:
  capacity:
    storage: "5Ti"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/hdd/shared/mediacenter/media/tv
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Ti"
  storageClassName: ""
  volumeName: tv
