apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
spec:
  capacity:
    storage: "4Ti"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /nfs/tv
    server: 192.168.8.202

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "4Ti"
  storageClassName: ""
  volumeName: tv
