apiVersion: v1
kind: Secret
metadata:
    name: navidrome
stringData:
    ND_USERNAME: ENC[AES256_GCM,data:WmW2AeU=,iv:snZ9ZKo5mKMNaqiE6hvXi3VMZU6YJL0el0KDet829pA=,tag:z+wLtWBP0CDKyw8VM8UrRQ==,type:str]
    ND_PASSWORD: ENC[AES256_GCM,data:N78PGtzCEZprg2Q=,iv:UMRUJnc3QajTndhO8AEv+yMyDyz/x3eizcjNdjWWW3U=,tag:JoUvSMCq9YTuKIBEHSeAYA==,type:str]
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:mZC/MCmWrXy1GQ9B7N37QV7h8v0yHqQ1s2eS7UaIAPk=,iv:bA1GPqc08nFYoW50fZcgCaQ9yyMdNuHvHb2cUiEs57w=,tag:8hVC1G6q53hmTGEWlOT+bw==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:SNFPQECpMufR7MjVoNhNFOMprDt8ACtwNA8KUTj75XM=,iv:2ihJplk+nj/w6YJCSFehnKL/DB06jVjb95cGGZmY1FI=,tag:NbiV6tmptVNAl4AniopzOA==,type:str]
sops:
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQUx4cjlBQWZjNGdocGcz
            eFFibThXME5PckpPSFJYT1FpVC9pdHFpMGtrClMxMGRiSXpla285dFVESGZFbkR2
            Q2ZGMDg0V0hlczBtRDNQNlVaR2l5eXMKLS0tIEYrZzg4N1pTTzNycERsdDVZYTlT
            YjJ6ZFlvU0EvVGJoZ1RvaW4xcStIQVUKtfODHo5s1hGJ/+6vwsR8d+Env/6KnEso
            VHInPkgby6DI7Sq7xe0Dmk4YJkmz2z9WDtiVqpRZ5UwUsWCB47dzeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T23:17:22Z"
    mac: ENC[AES256_GCM,data:KnA5GXZGGcVjMYherSeaC6ujCxVyv/11jfHQw6TZKPOIsx+oJQMOh2mpnIwbrZgTaXvZu0NrNFb9BxrKAQGj92o6dd51pl4T0EMZXnSEJojdbF/ME5G4k+oco6rXaW8hg49+FwZSeh31icAjuXI2zhnRrt3XrtEoLtFDKN3LOKE=,iv:FtjnywIGCZrZ1HzHlcoTs59q2SIdeLoRmRco1NNldjg=,tag:MO3sPlggVphYfX3sYhzS7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
