apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: navidrome
spec:
  selector:
    matchLabels:
      app: navidrome
  serviceName: navidrome
  replicas: 1
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      containers:
        - name: navidrome
          image: deluan/navidrome
          env:
            - name: ND_BIND_ADDR
              value: "0.0.0.0"
            - name: ND_REVERSEPROXY
              value: "false"
            - name: ND_BASEURL
              value: ""
            - name: ND_LISTENBRAINZ_ENABLED
              value: "true"
            - name: ND_LISTENBRAINZ_BASEURL
              value: "https://koito.taild304c8.ts.net/apis/listenbrainz/1"
          envFrom:
            - secretRef:
                name: navidrome
          ports:
            - name: http
              containerPort: 4533
          volumeMounts:
            - name: navidrome-config
              mountPath: /data
            - name: music
              mountPath: /music
      volumes:
        - name: music
          persistentVolumeClaim:
            claimName: music
  volumeClaimTemplates:
    - metadata:
        name: navidrome-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
