apiVersion: v1
kind: Service
metadata:
  name: tdarr
spec:
  selector:
    app: tdarr
  ports:
    - name: http
      port: 80
      targetPort: 8265

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tdarr-tailscale
spec:
  defaultBackend:
    service:
      name: tdarr
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
      - tdarr
