apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tdarr
  namespace: media
spec:
  serviceName: tdarr
  replicas: 1
  selector:
    matchLabels:
      app: tdarr
  template:
    metadata:
      labels:
        app: tdarr
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: perf
                    operator: In
                    values: ["high"]
            - weight: 50
              preference:
                matchExpressions:
                  - key: perf
                    operator: In
                    values: ["medium"]
            - weight: 10
              preference:
                matchExpressions:
                  - key: perf
                    operator: In
                    values: ["low"]
      securityContext:
        fsGroup: 1000
      containers:
        - name: tdarr
          image: haveagitgat/tdarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: serverIP
              value: "0.0.0.0"
            - name: internalNode
              value: "true"
            - name: nodeID
              value: "internal"
          ports:
            - containerPort: 8265
              name: ui
            - containerPort: 8266
              name: server
          volumeMounts:        
            - mountPath: /app/configs
              name: config
            - mountPath: /app/logs
              name: logs
            - mountPath: /temp
              name: temp
            - mountPath: /movies
              name: movies
            - mountPath: /tv
              name: transcoded-movies
            - mountPath: /transcoded-movies
      volumes:          
        - name: logs
          emptyDir: {}
        - name: temp
          emptyDir: {}
        - name: movies
          persistentVolumeClaim:
            claimName: movies            
        - name: tv
          persistentVolumeClaim:
            claimName: tv
        - name: transcoded-movies
          persistentVolumeClaim:
            claimName: transcoded-movies
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: longhorn
        resources:
          requests:
            storage: 10Gi