apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  annotations:
    metallb.io/loadBalancerIPs: 192.168.8.230
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-tailscale
  annotations:
    tailscale.com/funnel: "true"
spec:
  defaultBackend:
    service:
      name: jellyfin
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
      - jellyfin
