apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  serviceName: jellyfin
  replicas: 1
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: perf
                    operator: In
                    values: ["high"]

            - weight: 50
              preference:
                matchExpressions:
                  - key: perf
                    operator: In
                    values: ["medium"]

            - weight: 10
              preference:
                matchExpressions:
                  - key: perf
                    operator: In
                    values: ["low"]
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          lifecycle:
            postStart:
              exec:
                command: 
                  - "/bin/sh"
                  - "-c"
                  - |
                    apt-get update
                    VENDOR_ID=$(cat /sys/class/drm/card0/device/vendor)

                    
                    if [ "$VENDOR_ID" = "0x8086" ]; then
                        echo "Intel. Installing Intel OpenCL and Media drivers"
                        apt-get install -y intel-opencl-icd intel-media-va-driver-non-free
                    elif [ "$VENDOR_ID" = "0x1002" ]; then
                        echo "AMD. Installing Mesa OpenCL drivers"
                        apt-get install -y mesa-opencl-icd
                    else
                        echo "Unknown hardware ($VENDOR_ID). Installing generic Mesa drivers"
                        apt-get install -y mesa-va-drivers mesa-opencl-icd
                    fi
          resources:
            requests:
              cpu: "1000m"
              memory: "4Gi"
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
          ports:
            - name: http
              containerPort: 8096
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: tv
              mountPath: /tv
            - name: movies
              mountPath: /movies
            - name: serien
              mountPath: /serien
            - name: jellyfin-cache
              mountPath: /cache
            - name: dri
              mountPath: /dev/dri
            - mountPath: /dev/shm
              name: shm
      volumes:
        - name: tv
          persistentVolumeClaim:
            claimName: tv
        - name: movies
          persistentVolumeClaim:
            claimName: movies
        - name: serien
          persistentVolumeClaim:
            claimName: serien
        - name: dri
          hostPath:
            path: /dev/dri
        - name: jellyfin-cache
          emptyDir: {}
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: jellyfin-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
