apiVersion: v1
kind: Secret
metadata:
    name: mullvad-vpn
    # Use the same namespace as slskd
    namespace: media
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:QIDq/5WdiSBEA/ZBhgYGDoDO/Z8R+tiTrQVWj8h/xZiYFQpWl2f14X5E3vc=,iv:xUtMysZDMvxcdj1eoOnhMwbrUCSySA/QpCNaDEYV8Bs=,tag:KqTFv8cuSxctnkIYUQZZ3A==,type:str]
    address: ENC[AES256_GCM,data:5FcBys7uo7l9Jt81vMHN,iv:uDmPhIKbQFm7OiuvA/6jaGibh13McTXVzR+t3ccUrVA=,tag:OESpVvSg/9Phu22Un9MYlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TW1YU2Q5T0d5SUZHaGxy
            Tld3cDhVbytjMy95eVlvRms1WVR3OWZvK2trCjBTMWxuRTVsWCt6T1htZSthaEtt
            L2hhWnRWclhlSGZRbEhESU54NiszdjAKLS0tIEtUam9EamZhR3E3RzhtWVlKWjFm
            aUQrSmRWalV4SjJGU1g2RUczYU9KY2cKcNnUzfA4QjZZLL6OsICrPDMO+Je/a/a3
            +xIKvn0Ywm1ropCm6zuwCMnM4VWHLP2wfr4XW8ivLM41WDuU66rCxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T13:17:57Z"
    mac: ENC[AES256_GCM,data:YXhQg8NNtgKLeJ+2MG3ticxmTKrrEH4dwmbcOOewtHClU2I0sYAtG53N1NbytI6h8ix1Uv8lf5KNRlHJVcP6LZKZVR6PECfmb7/CX0d6GR/nDusnebqAKevvrvjLcie9rpoKeExj92L1fsXu3IXKQW4ti5iKiECEDyogojA7wXU=,iv:HDTgcDJQBQr+MAxXPeDChuI4n8XaFkdHCwVBbQPMZXY=,tag:GiewsHqgRf0kRFquOZYJRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
