apiVersion: v1
kind: Secret
metadata:
    name: mullvad-vpn
    # Use the same namespace as slskd
    namespace: media
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:K9jaDFvNd4V+tpW1tR8HKjCnYDuOcinLcNXwDCZmJFlB4spLRQcXfcCeoSc=,iv:SLuJcgNZPJ24w6PNMYjiM/KdIrv30PeuwpbSQ/sDAtY=,tag:WVjbFqA24jqpQjl4bXwwgA==,type:str]
    wireguard-address: ENC[AES256_GCM,data:kgp2oOGR+Qsve2v+0jehEg==,iv:85vYdudgXpV/52ZjsKQfXLK6HBXFezxjeJ4On6Ekdag=,tag:vzNhKeT2eHYEjgOMdJb6pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TW1YU2Q5T0d5SUZHaGxy
            Tld3cDhVbytjMy95eVlvRms1WVR3OWZvK2trCjBTMWxuRTVsWCt6T1htZSthaEtt
            L2hhWnRWclhlSGZRbEhESU54NiszdjAKLS0tIEtUam9EamZhR3E3RzhtWVlKWjFm
            aUQrSmRWalV4SjJGU1g2RUczYU9KY2cKcNnUzfA4QjZZLL6OsICrPDMO+Je/a/a3
            +xIKvn0Ywm1ropCm6zuwCMnM4VWHLP2wfr4XW8ivLM41WDuU66rCxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T16:13:55Z"
    mac: ENC[AES256_GCM,data:bS88vlk98pxw3ZIqQeMOzldNppNC05wnbdl+JPkvEA6WU4mR17ZMDjSrX8E86wHWDra1MuuvQyBdOOTHqKTbUpKoxJjpq5xjb5P2LjZ2wfGIz+SU84LBWrl4Wy02zycHvbMl2u2kRMvgEl5z/SUuVqDjZIjdzXr+eqdnsh0zhWU=,iv:K2Eh7YyLBupySRkuseFl2Y3U5xK2V4dai6dywOVu52Y=,tag:SfEh3TuNl2N1L0D4K0xGwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
