apiVersion: v1
kind: Service
metadata:
  name: slskd
spec:
  selector:
    app: slskd
  ports:
    - name: http
      port: 80
      targetPort: 5030
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slskd-tailscale
spec:
  defaultBackend:
    service:
      name: slskd
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - slskd
