apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slskd
  namespace: slskd
spec:
  serviceName: slskd
  replicas: 1
  selector:
    matchLabels:
      app: slskd
  template:
    metadata:
      labels:
        app: slskd
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: VPN_SERVICE_PROVIDER
              value: mullvad
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun-secrets
                  key: WIREGUARD_PRIVATE_KEY
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: wireguard-address
                  key: WIREGUARD_ADDRESSES
            - name: WIREGUARD_IMPLEMENTATION
              value: userspace
            - name: DOT
              value: "off"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "192.168.8.0/24"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: dev-tun
              mountPath: /dev/net/tun
          ports:
            - containerPort: 5030
              name: web
            - containerPort: 5031
              name: web-https
            - containerPort: 50300
              name: soulseek

        - name: slskd
          image: slskd/slskd
          env:
            - name: SLSKD_REMOTE_CONFIGURATION
              value: "true"
          volumeMounts:
            - name: config
              mountPath: /app
            - name: music
              mountPath: /music
            - name: downloads
              mountPath: /downloads

      volumes:
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: music
          nfs:
            server: 192.168.8.123
            path: /mnt/main/music
        - name: downloads
          nfs:
            server: 192.168.8.123
            path: /mnt/main/soulseek

  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
