apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slskd
spec:
  serviceName: slskd
  replicas: 1
  selector:
    matchLabels:
      app: slskd
  template:
    metadata:
      labels:
        app: slskd
    spec:
      containers:
        - name: vpn
          image: qmcgaw/gluetun
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: DNS_KEEP_NAMESERVERS
              value: "on"
            - name: DOT
              value: "off"
            - name: DNS_ADDRESS
              value: "10.43.0.10" 
            - name: VPN_SERVICE_PROVIDER
              value: mullvad
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_ENDPOINT_IP_FAMILY
              value: v4
            - name: WIREGUARD_MTU
              value: "1320"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: mullvad-vpn
                  key: private-key
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: mullvad-vpn
                  key: address
            - name: SERVER_COUNTRIES
              value: Sweden
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
            - name: FIREWALL_INBOUND_SUBNETS
              value: "0.0.0.0/0"
            - name: MTU_DISCOVERY
              value: "off"
            - name: WIREGUARD_MTU
              value: "1280"

          ports:
            - containerPort: 5030
              name: http

        - name: slskd
          image: slskd/slskd:latest
          env:
            - name: SLSKD_HTTP_URL
              value: "http://127.0.0.1:5030"
            - name: SLSKD_REMOTE_CONFIGURATION
              value: "true"
            - name: SLSKD_SOULSEEK_USERNAME
              value: "corneliust"
            - name: SLSKD_SOULSEEK_PASSWORD
              value: "Cornelius123"
          volumeMounts:
            - name: slskd-config
              mountPath: /app
            - name: downloads
              mountPath: /app/downloads
      
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: soulseek-download
  
  volumeClaimTemplates:
    - metadata:
        name: slskd-config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi