apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:t5xCi/bF3jWGqnGE8noYRTPw0tGMOKmtMtQt3gZciBVDiwEX3ZR2KoJqTIER0dxut5PeqDQ=,iv:r6db+J0ujAXK+sD24dJO26I8+syNby9toD5WtKwxVfo=,tag:uWggNSa7EG99HDOjm23zcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTklHNDBjK2Q2N0RLdlJI
            UzBoMzJ6cTZFQkRiYUh1OFNwUXNielpXOTEwCjdIZ1pCQXJiTmQzVFVkWlF2Mkhp
            WDlQSkVsSk1ZUXdYZ01tRy9wZWRYaGMKLS0tIEFGaHozT3RaeVE4amVCUTlwMk9W
            aG1NR0xCZjZTanV2NW52NmVqTXJuYnMKoKI5vems/PosQaOTbwWGO7N5QvIhkZvB
            8FT8tGOplNc4WDOHWnUncM6csG0Biss0BGDM1xG/JGNZKZsGOyumqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T22:17:25Z"
    mac: ENC[AES256_GCM,data:QOGUshEstotMwZ8Z+MXKBe4hd85rG3Jt+ic7Nu5UqABLI5breFrvRR8U70+PMITvgDdjoCv54a5I1k1HSvTnJw8VRHrZwZE2NRC49Ilp2WJs0B2n34nQ0dPVYf+eOlD5HIbBtJVJNa/tYB+3OQ2OtbTRpt9fTn1mpqzx6oVaPcM=,iv:Pdf9oPAVF9ZZduKKsLAqYvMuArgsjqQfIUKubplgbZo=,tag:YH2FR4Qd53bK6XA9894BUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
