  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: minecraft-jan
  spec:
    replicas: 1 # set to 1 later
    selector:
      matchLabels:
        app: minecraft-jan
    template:
      metadata:
        labels:
          app: minecraft-jan
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: perf
                      operator: In
                      values: ["high"]

              - weight: 50
                preference:
                  matchExpressions:
                    - key: perf
                      operator: In
                      values: ["medium"]

              - weight: 10
                preference:
                  matchExpressions:
                    - key: perf
                      operator: In
                      values: ["low"]
        containers:
          - name: minecraft-jan
            image: itzg/minecraft-server:latest
            env:
              - name: EULA
                value: "TRUE"
              - name: TYPE
                value: "NEOFORGE"
              - name: VERSION
                value: "1.21.1"
              - name: MEMORY
                value: "8G"
              - name: DIFFICULTY
                value: "normal"
              - name: OPS
                value: "Raph3001,roteKlaue"
              - name: WHITELIST
                value: "Raph3001,roteKlaue"
              - name: MODRINTH_PROJECTS
                value: "accessories,advanced-netherite,amendments,architectury-api,aures-farmers-structures,balm,caelus,carry-on,chefs-delight,cloth-config,coroutil,create,create-aeronautics,createaddition,create-deco,slice-and-dice,copycats,create-diesel-generators,create-enchantment-industry,cristel-lib,curios,cut-through,delight-lib,easy-piglins,easy-villagers,elytra-slot,elytra-trims,farmers-delight,forgified-fabric-api,geckolib,guard-villagers,iron-barrels,iron-furnaces,jamlib,jewelry,kotlin-for-forge,lithostitched,create-dragons-plus,mes-moogs-end-structures,moogs-structure-lib,moonlight,more-delight,moogs-voyager-structures,netherportalfix,owo-lib,polymorph,puzzles-lib,ranged-weapon-api,ribbits,rightclickharvest,sable,smarter-farmers-farmers-replant,spell-power,structure-pool-api,supplementaries,supplementaries-squared,tectonic,tidal-towns,towns-and-towers,waystones,yungs-api,zombie-awareness,zombie-variants"
            ports:
              - containerPort: 25565
                name: minecraft-jan
            volumeMounts:
              - name: data
                mountPath: /data
            resources:
              requests:
                memory: "4Gi"
                cpu: "1"
              limits:
                memory: "10Gi"
                cpu: "8"
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: minecraft-data-jan

# accessories,advanced-netherite,amendments,architectury-api,aures-farmers-structures,balm,caelus,carry-on,chefs-delight,cloth-config,coroutil,create,create-aeronautics,createaddition,create-deco,slice-and-dice,copycats,create-diesel-generators,create-enchantment-industry,cristel-lib,curios,cut-through,delight-lib,easy-piglins,easy-villagers,elytra-slot,elytra-trims,farmers-delight,forgified--api,geckolib,guard-villagers,iron-barrels,iron-furnaces,jamlib,jewelry,kotlin-for-forge,lithostitched,create-dragons-plus,mes-moogs-end-structures,moogs-structure-lib,moonlight,more-delight,moogs-voyager-structures,netherportalfix,owo-lib,polymorph,puzzles-lib,ranged-weapon-api,ribbits,rightclickharvest,sable,smarter-farmers-farmers-replant,spell-power,structure-pool-api,supplementaries,supplementaries-squared,tectonic,tidal-towns,towns-and-towers,waystones,yungs-api,zombie-awareness,zombie-variants,jei
