apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-jan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-jan
  template:
    metadata:
      labels:
        app: minecraft-jan
    spec:
      containers:
        - name: minecraft-jan
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "NEOFORGE"
            - name: VERSION
              value: "1.21.11"
            - name: MEMORY
              value: "8G"
            - name: DIFFICULTY
              value: "normal"
            - name: OPS
              value: "Raph3001,roteKlaue"   # comma-separated op list
          ports:
            - containerPort: 25565
              name: minecraft-jan
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "8"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-data-jan
