apiVersion: v1
kind: Service
metadata:
  name: minecraft-jan
spec:
  selector:
    app: minecraft-jan
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-jan-tailscale
  annotations:
    tailscale.com/funnel: "true"
spec:
  defaultBackend:
    service:
      name: minecraft-jan
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
      - minecraft-jan
