apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
stringData:
    client_id: ENC[AES256_GCM,data:4JizLTLeqoVYEklagk5luXI=,iv:FAV3tDZQ+iNeBmO6SHL/etpHKIDEN34B9BgLz20cwoA=,tag:EMRGNpO0YHNhylBMaknoCw==,type:str]
    client_secret: ENC[AES256_GCM,data:F8Q9d8IUi0YYs6vVv7Zn43pJIl+SyTT9xpoAQN6loucofSMvyBFv53iBnTxB3R53Q2m4fb5iQ1coIlNqyI2v4Q==,iv:GzFBQTX142d4dpDohiV12Fi7QdrTRyZkZBsahlphsZs=,tag:FjlBjDS6v+lhJXu9AYooRA==,type:str]
sops:
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTFkrV1lkNnJka05ubk05
            RWZuSHZ3ZjA3eFFoLzRaZXk3ZzZ0bmdVZ21rCjRDT0hQeUdlckhHZGNJZlZ4eE9a
            ZTROK0c0UUxDcnR1bWhiYzVMbVhsWm8KLS0tIGpGK2EwbG5heml0ZFVMYklmRTgw
            WER5R1A5NVlmd24vR1hrN0pYTUU3ZVkK4UrBIdxGh3xN0J5cQPWTpVmHAmFQsjto
            x3Fp0a6+LZGQxaY64DBwk3xdApc9VAcP37fbSgth/rip/K/2kSKu6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T21:59:00Z"
    mac: ENC[AES256_GCM,data:+cCMaFE1/w2I+ddH3AfMOiy0B2Zim49QLu4AH44Oz7zi7boXhxwDwMtpNxeEFLU3choi60isuKnWjMIZsamtgxTnb1l+66Rfvi52N+sJ79ZECmzA7mPzJp6pmRCouvBFz1OWyNM7qqD/DUbcsGWO9ckuCfZWbnu8vUdeYJjuOhs=,iv:cEfJ2r14lWmcMKJ8/7Q1mm33sl59/vClWpFfTTT+5i4=,tag:afuCaaNRlhNf+3qPzRRvcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
