apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
stringData:
    client_id: ENC[AES256_GCM,data:W79v1Ek/RPBoCSdLlIHYy0o=,iv:H4TMAYvpc3VgDeyqkJePp0NOSuv0noUOv+nNHYf3y+Y=,tag:OOPQLWDU6eWRnq31CzzZkA==,type:str]
    client_secret: ENC[AES256_GCM,data:mG+VunE2Y/40vDHmU6KcryvrNMXLYkrwC5ucV8sAMRBYx6JGzYBl2jlxgMJHOk8Q90R1iJzfz2zr16bkbm2n,iv:hIkp02HeyyyteRP2lNPeUdRwEUeEgJtvsNTliJ0v7/w=,tag:Vpfbw4UCHJXDpCu8PIYfJg==,type:str]
sops:
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTFkrV1lkNnJka05ubk05
            RWZuSHZ3ZjA3eFFoLzRaZXk3ZzZ0bmdVZ21rCjRDT0hQeUdlckhHZGNJZlZ4eE9a
            ZTROK0c0UUxDcnR1bWhiYzVMbVhsWm8KLS0tIGpGK2EwbG5heml0ZFVMYklmRTgw
            WER5R1A5NVlmd24vR1hrN0pYTUU3ZVkK4UrBIdxGh3xN0J5cQPWTpVmHAmFQsjto
            x3Fp0a6+LZGQxaY64DBwk3xdApc9VAcP37fbSgth/rip/K/2kSKu6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T22:18:45Z"
    mac: ENC[AES256_GCM,data:NiFOiuSoH5y+Vs1XiMJD+1RKIGGDyfTW3m6BExcGbjqvXdpNAgWzmdr8b/ZeGMeztHvRhBiWm9dnboZuqPt9AkPojEy5nGx0cKEnkMRUDp0vbkHoxDT77NrDh37jG8CGYBLwj6nG5rwKg8BUU2f9UQXdB5jpAKNp8nhmB6vIhH0=,iv:JaU/uF+QoBKXO3P/33zjNnxqmovgTMeMX5ochuw1sHw=,tag:rRsFB5y7DOPLTog2eZlp2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
