apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    ingress:
      - hostname: jellyfin.raphael-bader.com
        service: http://jellyfin.media.svc.cluster.local:80

      - hostname: navidrome.raphael-bader.com
        service: http://navidrome.media.svc.cluster.local:80

      - hostname: matrix.raphael-bader.com
        service: http://matrix.element.svc.cluster.local:8008

      - hostname: openwebui.raphael-bader.com
        service: http://openwebui.llm.svc.cluster.local:80

      - service: http_status:404
