apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:XaqDMqFEj/vCj9NLqPSaL0cIXAOC0tbCUVWVJT7CRHuweCAqF+MHK2ih1bk06dLdi5xxrAuLTRVK3BqPQlrkwr4FZySYcaCS/qdEroYNp/PkRvHlnnBKcpR/smXabngABy2ObJ55DxekekAvyfL9IFn8khGHD4HaUi46exM1aCvnlUjsOUKTGGqv4cdHGncZ5gKvT3Xr/dcYrBgeYNpqm2qeZ6lizFfTm2qzT0O97KSWGpAf4lP9Fg==,iv:B6M6eM6CUl2vVSyD9MMKvlcVTBgxJtbtiEiSm6p30wg=,tag:iPvKJRJp9XBvmQVMH4aCnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNzJwSjhuSTkvOGZaVlo3
            V2ZzNk1NYnZSclBBenZKd25kbVo0TFJZR2drCnJnOHk5WUhjQUxoTVhPeVZ6SG1z
            N0pNZ2F4aW04SFZtSGFrOFhIV3Q4VDgKLS0tIGdtc1JMR2M4NjFwQlRCWGw2MEd2
            elBQRUZZbnpBRU1KS09lZlpOMnZBZGsK+8WBfFFQu++9baXR5dQPJyxlv9GlXud2
            Bvg8qFNtw3632iV0H8+SyRAWFqw6kZ22c43LaObbhVMbwFe7lFUyhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T11:17:12Z"
    mac: ENC[AES256_GCM,data:0cs7qBRNRGps/6Tg+wFYKESlAWdqChRz4bciuD4AmWURxbRFSCywfn44XcmqOFCZxM/hHBCfQZsTiNp+CUC1f14dCtTEczwXdYzGwaB3yBtSzcyuhGFmfFxjWPywrkAcYpSDoJ3wlvv73uUnGAIKHus9HkU/hF0ZLj3JF8SVl9A=,iv:0hhEl6A1KjLyEu+cgAf5gxokNB5OIwW49WFD0Wrk99k=,tag:V0sZXcr2rJ7g+iPxr6HsSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
