apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:efJUOq16nIHEuNzoLpA7cSY5K5Dm0FAqpcto9Uc+mWeswmRLLA+QZPWxLG/4QwZ48qZq1GYK5selh3wpWu+fFC9Xy3LDPgZmvJAjT05faFRxMDHArMScq1974RG9ssd73Y972LGlqRD51/FYYOJSbzMJLpJWEbZCUxFgI6+VUEl/bMfVdF26t4WvvB9+WgjPHgTm0o/vmcKEXtTh1zizZZrhpEmsjS3iRdFGaTdVD5r88zY=,iv:5rZr7dm19uPDa3EaIxSW33ZTZyQpYDTlFbnrDIPGoHY=,tag:wl+YaR5tVzd9/ls+4JHRew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNzJwSjhuSTkvOGZaVlo3
            V2ZzNk1NYnZSclBBenZKd25kbVo0TFJZR2drCnJnOHk5WUhjQUxoTVhPeVZ6SG1z
            N0pNZ2F4aW04SFZtSGFrOFhIV3Q4VDgKLS0tIGdtc1JMR2M4NjFwQlRCWGw2MEd2
            elBQRUZZbnpBRU1KS09lZlpOMnZBZGsK+8WBfFFQu++9baXR5dQPJyxlv9GlXud2
            Bvg8qFNtw3632iV0H8+SyRAWFqw6kZ22c43LaObbhVMbwFe7lFUyhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T22:22:20Z"
    mac: ENC[AES256_GCM,data:9UuXa8ETl0vu1vxomqFUF92VwNaMJPBKZ3Cvwv01noM/M0ufHU7flVTyWbQYDxav6QcfPI+mB8OHK80ug59lJHIfz3PSq9otJ6E/wrC6MXyMNy9RMdlDoU82gkEUcZNwH/96eayq0SmgkvuW29xZiP3Yb58ql5D3n1s3G0aUBdA=,iv:CBnX8CEdkQzMzMYWbazJFkZfoWFIuTwMN+eu0favKwc=,tag:lq26BfaZHyXwuO/HoE2H+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
