apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:8tT/QT734n4yA6MYjdXOH8GUyKknO2q2TbqyE1rnWitJwWOUCOSgYgaubx9KxNL/tY2wI1yMJlFLDbHg+FYQ9ppAxFT2lTq0CH07uJ9RbdTPafUB2J+KKzyp5Oq/5AlLhsv0gntA5vzzLhMNxNbbMgwHy17fzR4MCwydcTE8cSyc14Ok2lGVFYwsS8Z2fRKR/U6XTbM2Vo58BJ02FxEzyg9D0k5xsN9UX3esTEKxwb0vcfB1l+xT/w==,iv:tLNHh/0nZmf7EkzvcNdDeccJpRO9rJw/yzZsidCd9HA=,tag:7mPn+Q/P6Ijjkf4bKa4vpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNzJwSjhuSTkvOGZaVlo3
            V2ZzNk1NYnZSclBBenZKd25kbVo0TFJZR2drCnJnOHk5WUhjQUxoTVhPeVZ6SG1z
            N0pNZ2F4aW04SFZtSGFrOFhIV3Q4VDgKLS0tIGdtc1JMR2M4NjFwQlRCWGw2MEd2
            elBQRUZZbnpBRU1KS09lZlpOMnZBZGsK+8WBfFFQu++9baXR5dQPJyxlv9GlXud2
            Bvg8qFNtw3632iV0H8+SyRAWFqw6kZ22c43LaObbhVMbwFe7lFUyhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:34:07Z"
    mac: ENC[AES256_GCM,data:SqzY79W0BAR9kRXiDivAM4Wkk8qgOA8pJQUONUyf/3t0WxSW+TXsmXJrj8DEfNYz30xp46fmvDTay7UEUj9TDQoT6PuC1KZ4+6pICiWhWdqCb0oxQZwLXT9H8OLDIowJ0VJb0ny6mymq4Y8y3rQvN+R2SbLj0S8SktdFaAHUcSE=,iv:lfAPOgJCrAnHe93F83dwqT59WzVMjeRRansUDIPOGT4=,tag:+e6FuNktiejLgj+BpVyncg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
