apiVersion: v1
kind: Secret
metadata:
    name: navidrome-alex
stringData:
    ND_USERNAME: ENC[AES256_GCM,data:WmW2AeU=,iv:snZ9ZKo5mKMNaqiE6hvXi3VMZU6YJL0el0KDet829pA=,tag:z+wLtWBP0CDKyw8VM8UrRQ==,type:str]
    ND_PASSWORD: ENC[AES256_GCM,data:80v1yPKimPY9FjHdeajAgTMxpR4=,iv:M69ewma+da7KWTqLfCuBnjjQ9ElmqWO4f0QtOxE5khk=,tag:Uza2sH2pOyJhOw9f7F3xjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQUx4cjlBQWZjNGdocGcz
            eFFibThXME5PckpPSFJYT1FpVC9pdHFpMGtrClMxMGRiSXpla285dFVESGZFbkR2
            Q2ZGMDg0V0hlczBtRDNQNlVaR2l5eXMKLS0tIEYrZzg4N1pTTzNycERsdDVZYTlT
            YjJ6ZFlvU0EvVGJoZ1RvaW4xcStIQVUKtfODHo5s1hGJ/+6vwsR8d+Env/6KnEso
            VHInPkgby6DI7Sq7xe0Dmk4YJkmz2z9WDtiVqpRZ5UwUsWCB47dzeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T23:40:26Z"
    mac: ENC[AES256_GCM,data:IEcUKJjJns2MUhGE/v1N1Ve3I1opFvOD72bNMac8+johFWqUNT9Gu9zi91SECeV2FmH0gX8JkDo4QqCA0q0sFNXhHzDosSLoa0m7vHeVD7ag3zsXjgdRQW4DdYlOeXuhOoQCy6+tAWMgX04cqwZ4nIGPs1hXyXkHXKwhXtdOvyg=,iv:XAI7586bJZshi7Gz/1oxj0BFN020aNpPXJ2zy4xjmFw=,tag:ZzrWW/Y2FbrUuNoAWNUAqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
