apiVersion: v1
kind: Secret
metadata:
    name: navidrome
stringData:
    ND_USERNAME: ENC[AES256_GCM,data:WmW2AeU=,iv:snZ9ZKo5mKMNaqiE6hvXi3VMZU6YJL0el0KDet829pA=,tag:z+wLtWBP0CDKyw8VM8UrRQ==,type:str]
    ND_PASSWORD: ENC[AES256_GCM,data:UaSW1T5ZUSqhw7pTqb8K9oxSjmw=,iv:mpVlGReZwadhBFGxoMN8PChD8eZCApp60F2FLYueq7I=,tag:QckvcC+TJJnDEV5ic9zNBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkl0k8ndnpsu2ufc3sfh63u025clw6t254tpkjg77e026f9n6q5se3jz6p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQUx4cjlBQWZjNGdocGcz
            eFFibThXME5PckpPSFJYT1FpVC9pdHFpMGtrClMxMGRiSXpla285dFVESGZFbkR2
            Q2ZGMDg0V0hlczBtRDNQNlVaR2l5eXMKLS0tIEYrZzg4N1pTTzNycERsdDVZYTlT
            YjJ6ZFlvU0EvVGJoZ1RvaW4xcStIQVUKtfODHo5s1hGJ/+6vwsR8d+Env/6KnEso
            VHInPkgby6DI7Sq7xe0Dmk4YJkmz2z9WDtiVqpRZ5UwUsWCB47dzeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T23:09:46Z"
    mac: ENC[AES256_GCM,data:0UodbsxCWY9IsOEqSYm29HBnKlrbO0D5mAifpUKE10Ed1SEt2suBMiC92ISGWbyyeuf7YLLXvM/BlB3HtBXcozR/FnlMsAhjFOAaCsWn5PcAGis9NPhVsDAGEt2tbTjKZIJg643UT6Gafw/2QsqF5gM493q0qrTUY18ggA0TYEI=,iv:Tbnf967/tz3NrQAGduewikcA1+AH3E5UspkLfyTjOPg=,tag:Vbd56gYnunvgP6TeBxBhew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
