apiVersion: v1
kind: Service
metadata:
  name: navidrome-alex
spec:
  type: ClusterIP
  selector:
    app: navidrome-alex
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome-alex-internal
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - navidrome-alex.raphael-bader.com
      secretName: navidrome-alex-tls
  rules:
    - host: navidrome-alex.raphael-bader.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome-alex
                port:
                  name: http

